# Generated by Django 4.2.23 on 2025-11-09 07:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_user_date_joined"),
    ]

    operations = [
        migrations.AddField(
            model_name="playerprofile",
            name="theme_preference",
            field=models.CharField(
                choices=[("light", "Light"), ("dark", "Dark")],
                default="light",
                help_text="User theme preference (light or dark mode)",
                max_length=10,
            ),
        ),
    ]
