# Generated by Django 4.2.23 on 2026-01-04 01:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_add_verification_method_and_email_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="firebase_uid",
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
    ]
